export const icons = {
    apple: require("./icons/apple.png"),
    arrowright: require("./icons/arrowright.png"),
    bluecheck: require("./icons/bluecheck.png"),
    camera: require("./icons/camera.png"),
    container: require("./icons/container.png"),
    externaldrive: require("./icons/externaldrive.png"),
    facebook: require("./icons/facebook.png"),
    google: require("./icons/google.png"),
    graph: require("./icons/graph.png"),
    homeBg: require("./icons/homeBg.png"),
    lock: require("./icons/lock.png"),
    logo: require("./icons/logo.png"),
    messages: require("./icons/messages.png"),
    shield: require("./icons/shield.png"),
    sms: require("./icons/sms.png"),
    tickcircle: require("./icons/tickcircle.png"),
    user: require("./icons/user.png"),
    Img: require("./icons/Img.png"),
    people: require("./icons/people.png"),
    homeImgBg: require("./icons/homeImgBg.png"),
    leftBg: require("./icons/leftBg.png"),
    rightBg: require("./icons/rightBg.png"),

};
